version: '3'

services:
  aeon_php:
    build: ./php
    container_name: aeon_php
    volumes:
      - ${PHP_WEBROOT}:/var/www/html
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - aeon_db
  aeon_db:
    image: mysql:latest
    container_name: aeon_db
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./mysql/dumps:/dumps
      - ./mysql/data:/var/lib/mysql
