version: '3'

services:
  aeon_php:
    build: ./php
    container_name: aeon_php
    command:
      - /bin/sh
      - -c
      - |
        chown -R www-data:www-data ./partials_c
        export SERVER_NAME=localhost
        export APACHE_RUN_USER=www-data
        export APACHE_RUN_GROUP=www-data
        export APACHE_PID_FILE=/var/run/apache2/apache2.pid
        export APACHE_RUN_DIR=/var/run/apache2
        export APACHE_LOCK_DIR=/var/lock/apache2
        export APACHE_LOG_DIR=/var/log/apache2
        export APACHE_LOG_LEVEL=warn
        exec apache2 -DFOREGROUND
    volumes:
      - ${PHP_WEBROOT}:/var/www/html
    ports:
      - 8080:80
    env_file: .env
    depends_on:
      - aeon_db
  aeon_db:
    image: mysql:latest
    container_name: aeon_db
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./mysql/dumps:/dumps
      - ./mysql/data:/var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d/:ro
